### ISSUE TITLE
Issue with Point 1

### ISSUE THREAD

**Issue by simonefacchiano** [jonasbarth/adm-2022-hw-5#2]
To get started, you have to download the data, as always, from [here](https://www.kaggle.com/datasets/csanhueza/the-marvel-universe-social-network?select=hero-network.csv). Make sure you downloaded all files because we will work with them all.

In particular, the files contain the following:  
- __nodes.csv__ - Contains two columns (node, type), indicating the nodes' name and type (comic, hero).
- __edges.csv__ - Contains two columns (hero, comic), indicating which comics the heroes appear in.
- __hero-network.csv__ - Contains the network of heroes who have appeared together in the comics.

### Graphs setup

For this homework, we are going to build two different graphs:  

1. __First graph__: Will be constructed using the data stored in the __'hero-network.csv'__ file, in which an edge between two heroes can be found if they have appeared in the <ins> same comic together</ins>. The <ins>number of edges</ins> between two heroes represents the <ins>number of times they have collaborated</ins> in different comics. The graph should be considered __weighted__ and __undirected__. It is up to you to decide which metric to use to calculate the weights, but we anticipate that the cost will be __lower__ for heroes with __more collaborations__. Please specify which metric you used to select the weights in the report.

2. __Second graph__: The data in 'nodes.csv' and 'edges.csv' will be used to construct the second graph. The type of node (hero/comic) can be found in __'nodes.csv'__, and an edge between a hero node and a comic node can be found in __'edges.csv'__ when the <ins>hero has appeared in that specific comic</ins>. This graph is assumed to be __undirected__ and __unweighted__.

### Data Preprocessing

As always, in the data science area, you can find some inconsistencies in the provided data. Therefore, some modifications should be made to the data to make it consistent across all of the datasets you have. To ensure consistency in the data, keep the following in mind:

1. Some of the heroes' names in 'hero-network.csv' are not found in 'edges.csv'. This inconsistency exists for the following reasons:
   
   - Some heroes' names in 'hero-netowrk.csv' have __extra spaces__ at the end of their names compared to their names in 'edges.csv'.
   - Some heroes' names in 'hero-netowrk.csv' have an __extra '/'__ at the end of their names compared to their names in 'edges.csv'.
   - The hero name __'SPIDER-MAN/PETER PARKER'__ in 'edges.csv' has been changed to __'SPIDER-MAN/PETER PAR'__ in 'hero-network.csv' due to a string length limit in 'hero-network.csv'.
 
2. Some entries in the 'hero-network.csv' have the same hero in <ins>both columns</ins>. In the graph, these entries form a __self-loop__. Because a self-loop makes no sense in this network, you can safely remove those from the dataset.

**Comment by jonasbarth** [comment]
Some questions I have:
* should our graph be a multigraph or not? In `hero-network.csv`, we have multiple edges per hero, but because we need to weight edges between heroes based on the number of collaborations, creating a multigraph doesn't actually make sense here.
![image](https://user-images.githubusercontent.com/32641360/208664330-5c655eb1-d93f-4e5c-b8d5-e23fc28557f8.png)

**Comment by jonasbarth** [comment]
> Some questions I have:
> 
> * should our graph be a multigraph or not? In `hero-network.csv`, we have multiple edges per hero, but because we need to weight edges between heroes based on the number of collaborations, creating a multigraph doesn't actually make sense here.
>   ![image](https://user-images.githubusercontent.com/32641360/208664330-5c655eb1-d93f-4e5c-b8d5-e23fc28557f8.png)

In the end I created a simple graph where nodes may only share a single edge. This edge is weighted according to number of comics that both heroes appeared in.

$$\lim_{n\to \infty}\frac{1}{n} = 0$$
